# package_list.yaml

- name: Install necessary packages
  hosts: all
  become: true
  tasks:
    - name: Install bind-utils package
      package:
        name: bind-utils
        state: present

    - name: Install man package
      package:
        name: man
        state: present

    - name: Install man-pages package
      package:
        name: man-pages
        state: present

    - name: Install mlocate package
      package:
        name: mlocate
        state: present

    - name: Install sysstat package
      package:
        name: sysstat
        state: present

    - name: Install vim package
      package:
        name: vim
        state: present

    - name: Install htop package
      package:
        name: htop
        state: present

    - name: Install net-tools package
      package:
        name: net-tools
        state: present
